config/routes.rb
Rails.application.routes.draw do
  root 'guilds#index'
  resources :characters
  resources :guilds do
    post :get_rating, on: :member
  end
end

app/models/character.rb
class Character < ActiveRecord::Base
  has_and_belongs_to_many :pets
  belongs_to :guild

  after_save :get_pets

  def get_pets
    url = "https://eu.api.battle.net/wow/character/#{self.guild.realm}/#{self.name}?fields=pets&locale=ru_RU&apikey=#{ENV['bnet_api_key']}"
    uri = Addressable::URI.parse(url)
    character = HTTParty.get(uri.normalize)

    if character['pets'].present?
      pets = character['pets']['collected']
      pets.each do |pet|
        find_pet = Pet.find_by(name: pet['name'])
        self.pets << find_pet if find_pet
      end
    end
  end
end

app/models/guild.rb
class Guild < ActiveRecord::Base
  has_many :characters, dependent: :destroy
  validates :name, presence: true
  validates :realm, presence: true

  serialize :rating, Array

  def from_api
    url = "https://eu.api.battle.net/wow/guild/#{self.realm}/#{self.name}?&locale=ru_RU&apikey=#{ENV['bnet_api_key']}"
    uri = Addressable::URI.parse(url)
    guild = HTTParty.get(uri.normalize)
  end

  def create_characters
    url = "https://eu.api.battle.net/wow/guild/#{self.realm}/#{self.name}?fields=members&locale=ru_RU&apikey=#{ENV['bnet_api_key']}"
    uri = Addressable::URI.parse(url)
    characters = HTTParty.get(uri.normalize)

    characters['members'].each do |char|
      self.characters.build(name: char['character']['name'])
    end
    save!
  end

  def get_rating
    rating = []
    Pet.find_each do |pet|
      n = 0
      characters.each do |char|
        n += 1 if char.pets.include?(pet)
      end
      rating << {pet.name => n}
    end
    rating
  end
end

app/models/pet.rb
class Pet < ActiveRecord::Base
  has_and_belongs_to_many :characters
  validates :name, presence: true, uniqueness: true

  def get_all
    pets = HTTParty.get("https://eu.api.battle.net/wow/pet/?locale=ru_RU&apikey=#{ENV['bnet_api_key']}")
    pets['pets'].each do |pet|
      Pet.create!(name: pet['name'], creature_id: pet['creatureId'], \
        can_battle: pet['canBattle'], family: pet['family'])
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: [:show, :edit, :update, :destroy]

  # GET /characters
  def index
    @characters = Character.all
  end

  # GET /characters/1
  def show
  end

  # GET /characters/new
  def new
    @character = Character.new
  end

  # GET /characters/1/edit
  def edit
  end

  # POST /characters
  def create
    @character = Character.new(character_params)

    if @character.save
      redirect_to @character, notice: 'Character was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /characters/1
  def update
    if @character.update(character_params)
      redirect_to @character, notice: 'Character was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /characters/1
  def destroy
    @character.destroy
    redirect_to characters_url, notice: 'Character was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_character
      @character = Character.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def character_params
      params.require(:character).permit(:name, :guild_id)
    end
end

app/controllers/guilds_controller.rb
class GuildsController < ApplicationController
  before_action :set_guild, only: [:show, :edit, :update, :destroy, :get_rating]

  # GET /guilds
  def index
    @guilds = Guild.all
  end

  # GET /guilds/1
  def show
    # @pets = Pet.all.to_a
    # @guildpets = @guild.characters.map(&:pets).to_a
    # @rating = @guild.get_rating.sort_by { |k| k["pet"] }
  end

  # GET /guilds/new
  def new
    @guild = Guild.new
  end

  # GET /guilds/1/edit
  def edit
  end

  # POST /guilds
  def create
    @guild = Guild.new(guild_params)
    @guild.from_api

    if @guild.save
      GetCharactersAndPetsJob.perform_later(@guild)
      redirect_to @guild, notice: 'Guild was successfully created.'
    else
      render :new
    end
  end

  def get_rating
    UpdatePetsRatingJob.perform_later(@guild)
    redirect_to @guild, notice: 'Rating will be updated soon.'
  end

  # PATCH/PUT /guilds/1
  def update
    if @guild.update(guild_params)
      redirect_to @guild, notice: 'Guild was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /guilds/1
  def destroy
    @guild.destroy
    redirect_to guilds_url, notice: 'Guild was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guild
      @guild = Guild.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def guild_params
      params.require(:guild).permit(:name, :realm)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/guilds_helper.rb
module GuildsHelper
end

app/views/characters/_form.html.erb
<%= form_for(@character) do |f| %>
  <% if @character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
      <% @character.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :guild_id %><br>
    <%= f.number_field :guild_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/characters/edit.html.erb
<h1>Editing Character</h1>

<%= render 'form' %>

<%= link_to 'Show', @character %> |
<%= link_to 'Back', characters_path %>

app/views/characters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Characters</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Guild</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @characters.each do |character| %>
      <tr>
        <td><%= character.name %></td>
        <td><%= character.guild_id %></td>
        <td><%= link_to 'Show', character %></td>
        <td><%= link_to 'Edit', edit_character_path(character) %></td>
        <td><%= link_to 'Destroy', character, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Character', new_character_path %>

app/views/characters/new.html.erb
<h1>New Character</h1>

<%= render 'form' %>

<%= link_to 'Back', characters_path %>

app/views/characters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @character.name %>
</p>

<p>
  <strong>Guild:</strong>
  <%= @character.guild_id %>
</p>

<% @character.pets.each do |pet| %>
  <li><%= pet.name %></li>
<% end %>

<%= link_to 'Edit', edit_character_path(@character) %> |
<%= link_to 'Back', characters_path %>

app/views/guilds/_form.html.erb
<%= form_for(@guild) do |f| %>
  <% if @guild.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@guild.errors.count, "error") %> prohibited this guild from being saved:</h2>

      <ul>
      <% @guild.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :realm %><br>
    <%= f.text_field :realm %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/guilds/edit.html.erb
<h1>Editing Guild</h1>

<%= render 'form' %>

<%= link_to 'Show', @guild %> |
<%= link_to 'Back', guilds_path %>

app/views/guilds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Guilds</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Realm</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @guilds.each do |guild| %>
      <tr>
        <td><%= guild.name %></td>
        <td><%= guild.realm %></td>
        <td><%= link_to 'Show', guild %></td>
        <td><%= link_to 'Edit', edit_guild_path(guild) %></td>
        <td><%= link_to 'Destroy', guild, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Guild', new_guild_path %>

app/views/guilds/new.html.erb
<h1>New Guild</h1>

<%= render 'form' %>

<%= link_to 'Back', guilds_path %>

app/views/guilds/show.html.erb
<div class="col-md-4">
  <p>
    <strong>Name:</strong>
    <%= @guild.name %>
  </p>

  <p>
    <strong>Realm:</strong>
    <%= @guild.realm %>
  </p>

  <% @guild.characters.each do |char| %>
    <li><%= link_to char.name, char %></li>
  <% end %>

  <%= link_to 'Edit', edit_guild_path(@guild) %> |
  <%= link_to 'Back', guilds_path %>
</div>
<div class="col-md-8">
  <%= form_for :get_rating, url: get_rating_guild_path(@guild) do |f| %>
    <%= f.submit 'Get rating' %>
  <% end %>
  <table class="table">
    <% @guild.rating.sort_by { |k| k.values }.reverse.each do |key| %>
      <tr>
        <td><%= key.keys.first %></td>
        <td>
          <% key.values.first.to_i.times do %>
            |
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Guildpets</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body class='container'>

<%= yield %>

</body>
</html>